- hosts: 172.31.24.166
  become: true
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: get_sonar.repo
      ansible.builtin.shell:
        cmd: sudo wget -O /etc/yum.repos.d/sonar.repo http://downloads.sourceforge.net/project/sonar-pkg/rpm/sonar.repo
        chdir: /home/ec2-user
    - name: Install Sonar
      yum:
        name: sonar
        state: present
    - name: start sonar
      systemd:
        name: sonar
        state: started
        daemon_reload: yes
        enabled: yes
